import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "PT Roofing And Renovations",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // 👈 points to your new PNG
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-HFWG093JH2"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-HFWG093JH2');
            gtag('config', 'AW-18490098103');

            // Google Ads lead conversion: phone and email link clicks
            document.addEventListener('click', function (e) {
              var link = e.target.closest && e.target.closest('a[href^="tel:"], a[href^="mailto:"]');
              if (link) {
                gtag('event', 'conversion', { 'send_to': 'AW-18490098103/pFj8COXrmI4dELeD4vBE' });
              }
            });
          `}
        </Script>
      </head>
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
